### PR TITLE
Added a button to go back to home [Solves #17]

### PR DESCRIPTION
**Pull request by parush-uppal**
Added a button to go back to home 
WhatsApp Image 2022-10-20 at 2 26 41 AM

### CODE REVIEW

**Comment by jagjit-1** [comment]
Hi parush,

Can you please use the route already defined for home instead of creating a new one

**Comment by jagjit-1** [comment]
The changes look good but the issues have to be solved in dev branch

**Comment by jagjit-1** [comment]
Can you make a new pr for that i'll merge it right away

**Comment by parush-uppal** [comment]
Could you please explain what changes are to be made before sending new pr i did not understand what you mean by dev branch

**Comment by jagjit-1** [comment]
The main/updated code for the site is on the dev branch instead of the main branch in github therefore all the changes are to be made in the dev branch

**Comment by parush-uppal** [comment]
Hi,I am a little bit new to this i have raised another pr in dev branch dont know if i did it right  or not because after rasing pr it is showing 
all commits of different author from past.If did wrong please guide

**Comment by jagjit-1** [comment]
There's conflicts in the new pr you created, the reason for conflicts is that you are trying to push changes you made in main branch to a different branch 
I recommend you to delete and make a new fork and then switch to frontend folder in dev branch, make changes in that and make a new pr

**Pull request closed without merging**
