### PR TITLE
Added Responsiveness

### PR DESCRIPTION
**Pull request by parush-uppal**

### CODE REVIEW

**Comment by jagjit-1** [comment]
hey @parush-uppal can you please make changes in the existing files instead of making new ones cuz there have been some changes which are not reflected in the new files

**Comment by parush-uppal** [comment]
I have only created the new file for the new navbar component and its css only which can only be used after adding backend to it rest all changes where made in same file

**Comment by jagjit-1** [comment]
I get it but there have been other merges on the old file which is not included in the new file you've created and also in general this is not the way to do it

**Comment by parush-uppal** [comment]
Hi, ya there will be conflicts in the pull request since this pull request was made long ago and and after that other pr were merged.
Since i don't have the proper backend knowledge required to make this work. I will be closing the pr and please re assign the issue

**Pull request closed without merging**
